language: objective-c
osx_image: xcode10.2
before_install:
  - gem install cocoapods
install:
  - ./install_swiftlint.sh
script:
  - gem install travis --no-document
  - travis lint .travis.yml --no-interactive
  - swiftlint
  - xcodebuild clean build -project SCNBezier.xcodeproj -scheme SCNBezier -destination "platform=iOS Simulator,name=iPhone X" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
  - pod lib lint
